### ISSUE TITLE
Markbot errors

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/kraken-good-accessibility#1]
@hellachella
I'm not sure what this markbot error means
![Screenshot 2020-09-28 103657](https://user-images.githubusercontent.com/55193211/94446410-9c996780-0176-11eb-985f-d5f3fb557836.jpg)
![Screenshot 2020-09-28 103826](https://user-images.githubusercontent.com/55193211/94446546-c783bb80-0176-11eb-9a1b-11a5580b4cc6.jpg)

**Comment by hellachella** [comment]
It means that you haven't assigned accessibility roles or labels. Review the videos and notes underneath the videos on learn the web. 

https://learn-the-web.algonquindesign.ca/topics/content-accessibility/#wai-aria-roles--properties

Also here is a cheat sheet to look over:
https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/

**Comment by AlexanderTahtadjian** [comment]
ok thanks
