### ISSUE TITLE
Same Markbot Errors

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/kraken-good-accessibility#2]
@hellachella
I tried adding some new code, but not only is it givivng me the same errors (which I still dont know how to fix) but its also taking really long to load.
![Screenshot 2020-09-28 103657](https://user-images.githubusercontent.com/55193211/95031015-6c276100-0681-11eb-950a-82f0952576a9.jpg)
![Screenshot 2020-09-28 103826](https://user-images.githubusercontent.com/55193211/95031017-6f225180-0681-11eb-9fc5-79a3c427a426.jpg)

**Comment by hellachella** [comment]
#### 1. Put the `ul` directly in the nav. No need for the extra div
```
        <nav role="navigation">
          <div> <!-- REMOVE -->
            <ul>
              <li class="first-child">
                <a href="chapter-xvii.html" aria-label="">
                  <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#prev"></use></svg></i>
                </a>
              </li>
              <li class="nth-child (2)">
                <a href="contents.html">
                  <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#contents"></use></svg></i>
                </a>
              </li>
              <li class="last-child">
                <a href="chapter-xix.html">
                  <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#next"></use></svg></i>
                </a>
              </li>
            </ul>
          </div>
        </nav>
```

#### 2. Add aria-labels to the `<a>` tags in your `<nav> <li>`. They are currently blank. aria labels read out the titles of links for screen readers. 

```
          <li>
            <a href="chapter-xvii.html" aria-label="Go to previous chapter"> <!-- ALSO FILL OUT THE OTHER LINKS -->
              <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#prev"></use></svg></i>
            </a>
          </li>
```

**Comment by AlexanderTahtadjian** [comment]
I did that but its still giving me this error, and its still taking too long to process
![Screenshot 2020-10-05 105001](https://user-images.githubusercontent.com/55193211/95095093-9ec07080-06f8-11eb-8e80-ca548dfb2d07.jpg)

**Comment by hellachella** [comment]
I just downloaded it and dropped it into Markbot and it passed. I'll grade it manually.

**Comment by hellachella** [comment]
Please close the issue

**Comment by AlexanderTahtadjian** [comment]
ok thanks
